//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPShareVideo.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SPShareVideo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SPShareVideo() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SPShareVideo.Resources.SPShareVideo", typeof(SPShareVideo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embed Video.
        /// </summary>
        internal static string ButEmbedVideo {
            get {
                return ResourceManager.GetString("ButEmbedVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embed Video.
        /// </summary>
        internal static string ButEmbedVideoAlt {
            get {
                return ResourceManager.GetString("ButEmbedVideoAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YouTube Video.
        /// </summary>
        internal static string ButFromAddress {
            get {
                return ResourceManager.GetString("ButFromAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YouTube Video.
        /// </summary>
        internal static string ButFromAddressAlt {
            get {
                return ResourceManager.GetString("ButFromAddressAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert a Video into the page .
        /// </summary>
        internal static string ButShareVideoAlt {
            get {
                return ResourceManager.GetString("ButShareVideoAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Video.
        /// </summary>
        internal static string ButShareVideoMenuAlt {
            get {
                return ResourceManager.GetString("ButShareVideoMenuAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Video.
        /// </summary>
        internal static string cui_ButShareVideo {
            get {
                return ResourceManager.GetString("cui_ButShareVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embed Video.
        /// </summary>
        internal static string cui_STT_ButEmbedVideo {
            get {
                return ResourceManager.GetString("cui_STT_ButEmbedVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YouTube Video.
        /// </summary>
        internal static string cui_STT_ButInsertVideoFromAddress {
            get {
                return ResourceManager.GetString("cui_STT_ButInsertVideoFromAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Video.
        /// </summary>
        internal static string cui_STT_ButShareVideo {
            get {
                return ResourceManager.GetString("cui_STT_ButShareVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embed Video.
        /// </summary>
        internal static string cui_STT_title_ButEmbedVideo {
            get {
                return ResourceManager.GetString("cui_STT_title_ButEmbedVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YouTube Video.
        /// </summary>
        internal static string cui_STT_title_ButInsertVideoFromAddress {
            get {
                return ResourceManager.GetString("cui_STT_title_ButInsertVideoFromAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        internal static string GrpVideo {
            get {
                return ResourceManager.GetString("GrpVideo", resourceCulture);
            }
        }
    }
}
